name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Check Types
        run: npm run check

      - name: Build
        run: npm run build
